export const EVENT_SNAPSHOT = 'SNAPSHOT';
export const EVENT_SHIP_ROUTE_CHANGED = 'SHIP_ROUTE_CHANGED';
export const EVENT_SHIP_ARRIVED = 'SHIP_ARRIVED';
export const EVENT_SHIP_CANCELLED = 'SHIP_CANCELLED';
export const EVENT_PLAYER_JOINED = 'PLAYER_JOINED';
export const EVENT_PLAYER_LEFT = 'PLAYER_LEFT';
export const EVENT_SUBSYSTEM_UPDATE = 'SUBSYSTEM_UPDATE';
